Simple scraper
NikWaltz/metrics-collector pull request #1
Opened 2022-07-05 17:28 UTC by NikWaltz

Simple scraper

2022-07-14 09:41 UTC, rktkov requested changes

2022-07-14 09:41 UTC, rktkov commented on internal/storage/storage.go
> +func (s *Storage) GetAll() Storage {
Метода возвращает экземпляр класса. Зачем он нужен, если можно сразу работать с экземпляром?

2022-07-14 09:41 UTC, rktkov commented on internal/api/api.go
> +	"fmt"
см. пост про порядок импорта - https://practicum-students.slack.com/archives/C03M8QT91D1/p1657701050055759

2022-07-14 09:41 UTC, rktkov commented on internal/api/api.go
> +	GetAll() storage.Storage
Стоит изменить на использование типов из пакета моделей.

2022-07-14 09:41 UTC, rktkov commented on internal/api/api.go
> +func (a *api) valueHandle(w http.ResponseWriter, r *http.Request) {
Я бы выбрал другое имя для обработчика.

2022-07-14 09:41 UTC, rktkov commented on internal/api/api.go
> +func (a *api) handle(w http.ResponseWriter, r *http.Request) {
Тут точно надо придумать другое имя для метода.

2022-07-14 09:41 UTC, rktkov commented on cmd/server/main.go
> +	"github.com/NikWaltz/metrics-collector/internal/api"
см. комментарий про порядок.

2022-07-14 09:41 UTC, rktkov commented on cmd/agent/main.go
> +	"bytes"
см. комментарий про порядок

2022-07-14 09:41 UTC, rktkov commented on cmd/agent/main.go
> +	for {
С учебной точки зрения было бы интереснее реализовать задачу отправки данных тоже в виде го-рутины с обменом информации между 2-мя горутинами через канал. 
Более того, при такой реализация возможна такая комбинация интервалов, что отправка произойдет раньше чем считывание метрик и будет ошибка работы с полем метрик.

2022-07-19 10:43 UTC, NikWaltz commented on internal/storage/storage.go
> +func (s *Storage) GetAll() Storage {
поправил работу с экземпляром

2022-07-19 10:43 UTC, NikWaltz commented on internal/api/api.go
> +	"fmt"
поправил импорты

2022-07-19 10:44 UTC, NikWaltz commented on internal/api/api.go
> +	GetAll() storage.Storage
перенес storage в модели

2022-07-19 10:44 UTC, NikWaltz commented on internal/api/api.go
> +func (a *api) handle(w http.ResponseWriter, r *http.Request) {
сделал getMetricsHandler

2022-07-19 10:45 UTC, NikWaltz commented on internal/api/api.go
> +func (a *api) valueHandle(w http.ResponseWriter, r *http.Request) {
сделал getValueHandler

2022-07-19 10:45 UTC, NikWaltz commented on cmd/server/main.go
> +	"github.com/NikWaltz/metrics-collector/internal/api"
поправил импорты

2022-07-19 10:46 UTC, NikWaltz commented on cmd/agent/main.go
> +	for {
сделал отдельные таски для скрейпинга и отправки

2022-07-19 11:41 UTC, NikWaltz commented on cmd/agent/main.go
> +	"bytes"
поправил импорты

2022-07-20 08:30 UTC, rktkov approved these changes

2022-07-21 09:20 UTC, merged