Added JSON api
NikWaltz/metrics-collector pull request #2
Opened 2022-10-04 05:47 UTC by NikWaltz

Added JSON api

2022-10-19 16:53 UTC, tmvrus requested changes
Не выполнено требование инкремента
```
принимать запросы в сжатом формате (HTTP-заголовок Content-Encoding)
```

2022-10-19 16:53 UTC, tmvrus commented on cmd/agent/main.go
> +	defaultReportInterval, _ := time.ParseDuration("10s")
нет смысла вызывать ParseDuration если мы и так знаем значение, гораздо проще объявить константы
```
const defaultPollInterval = time.Second*2
const defaultReportInterval = time.Second*10
```

2022-10-19 16:53 UTC, tmvrus commented on cmd/agent/main.go
> +		return nil
Ошибку надо хотя бы залогировать

2022-10-19 16:53 UTC, tmvrus commented on cmd/agent/main.go
> +	err := json.NewEncoder(body).Encode(*metrics)
тут берется ссылка от metrics, но в ф-ю уже и так передается ссылка на metrics, брать ссылку от ссылки нет никакого смысла

2022-10-19 16:53 UTC, tmvrus commented on cmd/server/main.go
> +	defaultDuration, _ := time.ParseDuration("300s")
это тоже хорошо бы сделать константой

2022-10-19 16:53 UTC, tmvrus commented on cmd/server/main.go
> +	log.Fatalln(myAPI.Run(cfg.Address))
не очень хорошая практика, даже если myAPI.Run не вернет ошибку, программа все равно завершится с кодом выхода 1, что для ОС означает ошибку выполнения, лучше проверить != и тогда уже вызывать/не вызывать Fatal

2022-10-19 16:53 UTC, tmvrus commented on internal/api/api.go
> +	}
Если у запроса не будет заголовка "Content-Type" то это условие не сработает и хендлер продолжит работу

2022-10-19 16:53 UTC, tmvrus commented on internal/api/api.go
> +		if _, ok := err.(*service.TypeError); ok {
для того что бы выполнять такое сравнение, в пакете errors есть метод Is, это будет обсуждаться дальше в курсе, но воспользоваться им рекомендую уже сейчас

2022-10-19 16:53 UTC, tmvrus commented on internal/api/api.go
> +	if r.Header.Get("Content-Type") != "" {
тут тот же самый вопрос, что будет если "Content-Type"  пустой

2022-10-19 16:53 UTC, tmvrus commented on internal/api/api.go
> +		}
тут хорошо бы ответить клиенту InternalError

2022-10-19 16:53 UTC, tmvrus commented on internal/api/api.go
> +	case "counter":
строки "gauge" и "counter" встречаются в проекте повсеместно, рекомендую сделать их константами в пакете model

2022-10-26 08:57 UTC, NikWaltz commented
> Не выполнено требование инкремента
> 
> ```
> принимать запросы в сжатом формате (HTTP-заголовок Content-Encoding)
> ```

Добавил decompress хендлер

2022-10-26 08:57 UTC, NikWaltz commented on cmd/agent/main.go
> +	defaultReportInterval, _ := time.ParseDuration("10s")
сделал константами

2022-10-26 08:57 UTC, NikWaltz commented on cmd/agent/main.go
> +		return nil
добавил логгирование ошибки

2022-10-26 08:57 UTC, NikWaltz commented on cmd/agent/main.go
> +	err := json.NewEncoder(body).Encode(*metrics)
исправил

2022-10-26 08:57 UTC, NikWaltz commented on cmd/server/main.go
> +	defaultDuration, _ := time.ParseDuration("300s")
сделал константой

2022-10-26 08:58 UTC, NikWaltz commented on cmd/server/main.go
> +	log.Fatalln(myAPI.Run(cfg.Address))
добавил if

2022-10-26 08:58 UTC, NikWaltz commented on internal/api/api.go
> +	}
поправил условие

2022-10-26 08:58 UTC, NikWaltz commented on internal/api/api.go
> +		if _, ok := err.(*service.TypeError); ok {
сделал через метод errors.As

2022-10-26 08:59 UTC, NikWaltz commented on internal/api/api.go
> +	if r.Header.Get("Content-Type") != "" {
исправил

2022-10-26 08:59 UTC, NikWaltz commented on internal/api/api.go
> +		}
добавил 500 ответ

2022-10-26 08:59 UTC, NikWaltz commented on internal/api/api.go
> +	case "counter":
вынес в константы model

2022-10-28 13:26 UTC, tmvrus approved these changes
Очень хорошо

2022-10-30 17:40 UTC, merged