Added hash
NikWaltz/metrics-collector pull request #3
Opened 2022-11-07 21:50 UTC by NikWaltz

Added hash

2022-11-14 20:53 UTC, tmvrus requested changes
Хорошая работа, но есть несколько замечаний.

2022-11-14 20:53 UTC, tmvrus commented on internal/service/db_service.go
> +		return nil
Дизайн этого блока потенциально ошибочный: если запросы будут идти в несколько потоков, то есть вероятность, что проверкой наличия счетчика и вставкой, другой поток успеет вставить счетчик с точно таким же именем,  тогда первый поток получит ошибку. 

Такое поведение можно исправить при помощи синтаксиса `...ON CONFLICT DO UPDATE value=EXCLUDE.value + value` 

такой запрос будет выполнен в рамках одной транзакции и конкурентного доступа не будет.

2022-11-14 20:53 UTC, tmvrus commented on internal/service/db_service.go
> +}
тут остается незакрытое соединение

2022-11-14 20:53 UTC, tmvrus commented on internal/service/db_service.go
> +func (s *dbService) NewConnection(ctx context.Context) (*pgx.Conn, error) {
Подход, при котором для каждого запроса создается новое соединение не самый оптимальный, создание нового соединения - дорогая операция с для приложения и БД.
В Go принята другая схема, при старте приложения создается пул из нескольких соединений (в нашем случае достаточно одного) и дальше идет работа только с этим пулом, это быстрее и проще для приложения и БД.

2022-12-06 07:49 UTC, NikWaltz commented on internal/service/db_service.go
> +		return nil
поправил

2022-12-06 07:50 UTC, NikWaltz commented on internal/service/db_service.go
> +}
поправил

2022-12-06 07:50 UTC, NikWaltz commented on internal/service/db_service.go
> +func (s *dbService) NewConnection(ctx context.Context) (*pgx.Conn, error) {
переделал на pgxpool

2022-12-07 15:25 UTC, underbek commented on cmd/agent/main.go
> +			response.Body.Close()
стоит завернуть в defer после получения response

2022-12-07 15:32 UTC, underbek commented on internal/api/api.go
> +
лучше написать 
```go
if err == nil {
  w.WriteHeader(http.StatusOK)
  return
}
```

2022-12-07 15:33 UTC, underbek commented on internal/api/api.go
> +		w.WriteHeader(http.StatusOK)
на самом деле http.StatusOK выставляется по дефолту, если невыставить иной статус. Так что можно не писать

2022-12-07 15:38 UTC, underbek approved these changes
В целом, хорошо!
Добавил несколько замечаний)

2022-12-12 11:52 UTC, NikWaltz commented on cmd/agent/main.go
> +			response.Body.Close()
у меня таска sendMetricsTask крутится в бесконечном for, defer не получится использовать в ней, вынес в функцию sendMetric

2022-12-12 11:52 UTC, NikWaltz commented on internal/api/api.go
> +
переписал чуток

2022-12-12 11:52 UTC, NikWaltz commented on internal/api/api.go
> +		w.WriteHeader(http.StatusOK)
убрал статус ок

2022-12-13 17:23 UTC, underbek approved these changes
Замечания исправлены - аппрув

2022-12-13 20:31 UTC, merged